### PR TITLE
ncp stuck on io.js 1.6.x in download step

### PR DESCRIPTION
**Pull request by zeitiger**
New major version of ncp fix that issue for me

### CODE REVIEW

**Comment by subesokun** [comment]
Hi @zeitiger, thanks for the pointer :+1: Would love to merge the PR but the commit message is a bit unsuitable. Could you issue another PR with some meaningful commit message?

**Comment by zeitiger** [comment]
done

**Comment by subesokun** [comment]
Awesome, thanks :) Will draft this evening a new release with your fix included.

**Comment by subesokun** [comment]
Published v0.3.3 which contains your fix.

**Comment by zeitiger** [comment]
great

**Pull request merged**
