### PR TITLE
Increase compat with other git hosts via variables in base URL

### PR DESCRIPTION
**Pull request by gerarde**
I'm using Visual Studio Team Services (VSTS), and want to use jspm-git to link to Git repositories hosted in VSTS.

Unfortunately, the URLs of Git repositories in VSTS don't follow the common URL standard where the Base URL and repo names are simply concatenated together, one after another.

In my case, I'm using Visual Studio Team Services, and the Git Repositories have a URL which follows the following format: `https://someaccount.visualstudio.com/DefaultCollection/PROJECTNAME/_git/REPOSITORYNAME`

Thus, this PR adds a change which allows two variables to be set in the base URL, and if detected, jspm-git will replace the placeholders instead of appending the repo name.

The two variables proposed are:
- `$$projName$$`: Project Name
- `$$repoName$$`: Repository Name

The values for the two variables are split from the provided `repo` variable.

For example, if my registry configuration used the following base URL:
`https://someaccount.visualstudio.com/DefaultCollection/$$projName$$/_git/$$repoName$$`

And I tried to install with the command `jspm mygit:AwesomeProject/SuperRepo`, the resulting repository URL to be used would be:
`https://someaccount.visualstudio.com/DefaultCollection/AwesomeProject/_git/SuperRepo`

### CODE REVIEW

**Comment by subesokun** [comment]
Hi @gerarde, thanks a lot for improving jspm-git! So far your PR looks good but I wonder if we should be using [sprintf](https://www.npmjs.com/package/sprintf-js) for injecting the variables into the base URL. This way it will be much more generic and covers more use cases. E.g. your URL would look then like

```
https://someaccount.visualstudio.com/DefaultCollection/%s/_git/%s
```
and then we could use vsprintf to format it

```
vsprintf(baseURL, repo.split('/'))
```

I'd like to introduce also a configuration flag like `formatter: 'sprintf'` so that you've to enable sprintf formatting explicitly via the advanced configurations of jspm-git.

**Comment by subesokun** [comment]
Sorry I've totally missed you last update of the PR :( PR looks great now and I'll try to release it by tomorrow.

**Comment by tauren** [comment]
@gerarde Thanks for your effort! We can merge this PR once you resolve conflicts. @subesokun

**Comment by subesokun** [comment]
@tauren, sorry for the late reply :( I've been quite busy lately but I've locally merged the PR already a few months ago and added some optimizations. Hope I can find my local changes again.

**Pull request closed without merging**
