### PR TITLE
changes for upcoming jspm 0.17

### PR DESCRIPTION
**Pull request by m4r71n**
See https://github.com/jspm/jspm-cli/blob/0.17/docs/registry-api.md
I'm not an expert and I'm not sure if all `return` statements are correct, but I got my npm packages installed with jspm 0.17.0-beta.5

### CODE REVIEW

**Comment by subesokun** [comment]
Awesome, thanks for your contribution! I'll try to have a look on it this weekend and hopefully be able to draft a beta release.

**Comment by m4r71n** [comment]
Thank you very much!

**Comment by subesokun** [comment]
Your changes + some other merge changes I did have landed in the branch https://github.com/Orbs/jspm-git/tree/jspm-0.17 and I've also created a beta tag for npm

```
npm install jspm-git@beta
```

Would be awesome if you could give me a feedback if it works for you :)

**Comment by m4r71n** [comment]
Thanks for your work and yes it works for me :+1:

**Comment by subesokun** [comment]
Great :) Closing this issue PR but feel free to report issues here regarding the beta release.

**Pull request closed without merging**
